// Generated by https://quicktype.io

export interface Astros {
    message: string;
    people:  Person[];
    number:  number;
}

export interface Person {
    name:  string;
    craft: string;
    displayWikiSec?: boolean
}

//-------------------------------------------------

export interface ISS {
    "@id":       string;
    "@type":     string;
    satelliteId: number;
    name:        string;
    date:        string;
    line1:       string;
    line2:       string;
}
//--------------------------------------------------


