// Generated by https://quicktype.io

export interface Astros {
    message: string;
    people:  Person[];
    number:  number;
}

export interface Person {
    name:  string;
    craft: string;
}

//-------------------------------------------------
